### ISSUE TITLE
Issue with rTorrent Socket Endpoint

### ISSUE THREAD

**Issue by fl0wfr** [Log1x/docker-rtorrent-flood#3]
Hi,

I noticed that I can get information from rTorrent Socket Endpoint, but I couldn't upload torrents from clients (for example Transdrone or nzb360), and instances like Sonarr or Radarr never get the information that a torrent download is finished.
If you need some logs, let me know.
And by the way I had to add --log-driver=none to the container, it's logging way too much (1TB of logs in a couple of days.

Best,

**Comment by Log1x** [comment]
I'm not entirely sure what needs changed on the `nginx` config to fix this– but I noticed the issue as well. I'd ideally like to get it working in nginx so rTorrent+Flood can continue to use the socket.

**Comment by zilexa** [comment]
Perhaps figuring out how this was solved here: https://github.com/romancin/rutorrent-flood-docker/blob/master/README.md will help? 

your image seems better for me since it is a no-nonsense setup without all the extras and just a single UI instead of Ru+Flood.. but I'm still on the default linuxserver/rutorrent image for now.

**Comment by Log1x** [comment]
I think it might be best to just remove nginx and default rTorrent to using the port instead of socket endpoint.

**Comment by Log1x** [comment]
Fixed in #8

**Comment by peroo** [comment]
I had a bunch of socket issues initially, but managed to resolve it by changing the temp paths in nginx.conf. Haven't had any issues since.
```
scgi_temp_path /tmp/scgi;
client_body_temp_path /tmp 1 2;
```
